version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./path/to/your/springboot-app
      dockerfile: Dockerfile
    image: my-spring-boot-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres

  frontend:
    build:
      context: ./path/to/your/angular-app
      dockerfile: Dockerfile
    image: my-angular-app:latest
    ports:
      - "4200:4200"  
    depends_on:
      - backend

volumes:
  postgres_data: